
name: Making Private Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simular Private Build para QA
        run: |
          echo "A iniciar o empacotamento das alterações..."
          echo "A enviar os ficheiros para o ambiente de testes (QA) da Neptune..."
          echo "Private Build concluída com sucesso!"
